<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Attendance Report – SEAVS</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1e293b; }

        .header { text-align: center; margin-bottom: 20px; padding-bottom: 14px; border-bottom: 2px solid #1a3a5c; }
        .header .logo-box { display: inline-block; background: #1a3a5c; color: #fff; font-size: 18px; font-weight: bold; width: 40px; height: 40px; line-height: 40px; border-radius: 8px; margin-bottom: 6px; }
        .header h1 { font-size: 16px; color: #1a3a5c; font-weight: bold; margin-bottom: 2px; }
        .header p  { font-size: 10px; color: #64748b; }

        .report-title { font-size: 13px; font-weight: bold; color: #1a3a5c; margin-bottom: 4px; }
        .report-meta  { font-size: 10px; color: #64748b; margin-bottom: 16px; }

        .summary { display: table; width: 100%; margin-bottom: 16px; border-collapse: collapse; }
        .summary-box { display: table-cell; width: 25%; padding: 10px 14px; border-radius: 6px; text-align: center; }
        .s-total    { background: #eff6ff; }
        .s-verified { background: #f0fdf4; }
        .s-rejected { background: #fff1f2; }
        .s-rate     { background: #fffbeb; }
        .summary-box .val  { font-size: 20px; font-weight: bold; display: block; }
        .summary-box .lbl  { font-size: 9px; color: #64748b; text-transform: uppercase; letter-spacing: .05em; }
        .s-total .val    { color: #1a3a5c; }
        .s-verified .val { color: #16a34a; }
        .s-rejected .val { color: #dc2626; }
        .s-rate .val     { color: #e8a020; }

        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        thead th {
            background: #1a3a5c; color: #fff;
            padding: 8px 10px; text-align: left;
            font-size: 9px; text-transform: uppercase; letter-spacing: .05em;
        }
        tbody tr:nth-child(even) { background: #f8fafc; }
        tbody tr:nth-child(odd)  { background: #ffffff; }
        tbody td { padding: 7px 10px; border-bottom: 1px solid #e2e8f0; font-size: 10px; }

        .badge { display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 9px; font-weight: bold; }
        .verified { background: #dcfce7; color: #166534; }
        .rejected { background: #fee2e2; color: #991b1b; }

        .footer { margin-top: 20px; padding-top: 10px; border-top: 1px solid #e2e8f0; text-align: center; font-size: 9px; color: #94a3b8; }
    </style>
</head>
<body>

    {{-- Header --}}
    <div class="header">
        <div class="logo-box">S</div>
        <h1>SEAVS – Smart Examination Attendance Verification System</h1>
        <p>Institute of Heavy Equipment and Technology (IHET) · Dar es Salaam, Tanzania</p>
    </div>

    <div class="report-title">Attendance Report</div>
    <div class="report-meta">
        Generated on: {{ now()->format('d M Y, H:i:s') }} &nbsp;|&nbsp;
        Generated by: {{ auth()->user()->name }} ({{ ucfirst(auth()->user()->role) }})
    </div>

    {{-- Summary Boxes --}}
    <table class="summary">
        <tr>
            <td class="summary-box s-total">
                <span class="val">{{ $summary['total'] }}</span>
                <span class="lbl">Total Records</span>
            </td>
            <td class="summary-box s-verified">
                <span class="val">{{ $summary['verified'] }}</span>
                <span class="lbl">Verified</span>
            </td>
            <td class="summary-box s-rejected">
                <span class="val">{{ $summary['rejected'] }}</span>
                <span class="lbl">Rejected</span>
            </td>
            <td class="summary-box s-rate">
                <span class="val">
                    {{ $summary['total'] > 0 ? round(($summary['verified'] / $summary['total']) * 100) : 0 }}%
                </span>
                <span class="lbl">Success Rate</span>
            </td>
        </tr>
    </table>

    {{-- Attendance Table --}}
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Student Name</th>
                <th>Reg. Number</th>
                <th>Course</th>
                <th>Examination</th>
                <th>Subject</th>
                <th>Date</th>
                <th>Time</th>
                <th>Supervisor</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($records as $i => $r)
            <tr>
                <td>{{ $i + 1 }}</td>
                <td><strong>{{ $r->student->full_name ?? '—' }}</strong></td>
                <td>{{ $r->student->reg_no ?? '—' }}</td>
                <td>{{ $r->student->course->name ?? '—' }}</td>
                <td>{{ $r->exam->name ?? '—' }}</td>
                <td>{{ $r->exam->subject->name ?? '—' }}</td>
                <td>{{ \Carbon\Carbon::parse($r->time)->format('d M Y') }}</td>
                <td>{{ \Carbon\Carbon::parse($r->time)->format('H:i:s') }}</td>
                <td>{{ $r->user->name ?? '—' }}</td>
                <td>
                    <span class="badge {{ $r->status === 'Verified' ? 'verified' : 'rejected' }}">
                        {{ $r->status }}
                    </span>
                </td>
            </tr>
            @empty
            <tr>
                <td colspan="10" style="text-align:center; padding:20px; color:#94a3b8;">
                    No attendance records found.
                </td>
            </tr>
            @endforelse
        </tbody>
    </table>

    {{-- Footer --}}
    <div class="footer">
        SEAVS – Smart Examination Attendance Verification System &nbsp;|&nbsp;
        IHET, Dar es Salaam, Tanzania &nbsp;|&nbsp;
        Protected under Tanzania Personal Data Protection Act (2022)
        &nbsp;|&nbsp; Page 1
    </div>

</body>
</html>
